1 task
Lesh79/formal-lang-course pull request #1
Opened 2024-09-06 19:08 UTC by Lesh79

### Выполнил первое задание курса
**Добавил модуль и тесты для него.**
**_Возможности модуля:_**

- По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.
- По количеству вершин в циклах и именам меток строить граф из двух циклов и сохранять его в указанный файл в формате DOT.
_Студент: Ахметов Темерлан_

2024-09-07 15:49 UTC, WoWaster requested changes

2024-09-07 15:49 UTC, WoWaster commented on project/graph_module.py
> +        Graph.save_graph_dot(graph, path)
Вообще, просили функции, а не статические методы. И дальше такие вещи точно не прокатят

2024-09-07 15:49 UTC, WoWaster commented on requirements.lock
> -#   universal: true
А как вот это случилось без изменений в `pyproject.toml`? Были проблемы какие-то с резолвингом зависимостей? Мне очень не нравится факт, что в разных форках могут быть файлы лока зависимостей

2024-09-07 17:10 UTC, Lesh79 commented on project/graph_module.py
> +        Graph.save_graph_dot(graph, path)
Сейчас мне изменить?

2024-09-07 17:14 UTC, Lesh79 commented on requirements.lock
> -#   universal: true
Возможно я сам изменял `pyproject.toml` и что обновил `.lock`, а потом понял что херню сделал и вернул в прежний вид `pyproject.toml`, но обратно забыл((

2024-09-07 18:45 UTC, WoWaster commented on requirements.lock
> -#   universal: true
Верни обратно lock файл тогда, чтобы потом оно жуткими merge конфликтами не вспыло, ну и не маячило в диффах

2024-09-07 18:45 UTC, WoWaster commented on project/graph_module.py
> +        Graph.save_graph_dot(graph, path)
Угу (ну, вроде и так уже сделал)

2024-09-08 16:24 UTC, WoWaster approved these changes

2024-09-09 11:28 UTC, merged