Add finite automata module
Lesh79/formal-lang-course pull request #2
Opened 2024-09-13 18:09 UTC by Lesh79

### Выполнил второе задание курса
**Добавил модуль и тесты для него.**
**_Возможности модуля:_**

- Построение минимального детерминированного конечного автомата по заданному регулярному выражению.
- Построение недетерминированного конечного автомата по графу.

#### Студент: Ахметов Темерлан

2024-09-14 07:16 UTC, WoWaster requested changes
Было бы идеально, если бы ещё автотесты работали.

2024-09-14 07:16 UTC, WoWaster commented on tests/test_build_dfa.py
> +        print("build dfa from loaded graph")
Не уверен, что это хоршая идея.

2024-09-14 08:45 UTC, Lesh79 commented on tests/test_build_dfa.py
> +        print("build dfa from loaded graph")
Именно тест с уже существующим графом?

2024-09-14 09:28 UTC, WoWaster commented on tests/test_build_dfa.py
> +        print("build dfa from loaded graph")
`print` в теле теста

2024-09-15 10:16 UTC, WoWaster approved these changes

2024-09-15 12:46 UTC, merged